### ISSUE TITLE
Can you explain how to edit `ssh.tar.gz`?

### ISSUE THREAD

**Issue by miticollo** [verygenericname/sshtars#2]
For now I tried to uncompress archive and then compress again without new files. I used your `gtar` for both tasks. But when I run `./sshrd.sh boot` on iPad Pro after verbose boot Apple logo with progress bar appears. Obviously `./sshrd.sh ssh` doesn't work.  Where do I make mistake?

As iOS version I used 15.7.

**Comment by ghost** [comment]
extract all files and contents from sshtars dir
```
mkdir work
cp ssh.tar.gz work/ssh.tar.gz
cd work
tar -xzvf ssh.tar.gz
rm ssh.tar.gz
```
compress all files and contents from work dir
```
tar -czvf ssh.tar.gz *
rm ../ssh.tar.gz
cp ssh.tar.gz ../ssh.tar.gz
cd ..
```
tested and works on iphone 6s ios 15.6.1
