### ISSUE TITLE
can you make it not auto restart when installing TrollStore or Pogo

### ISSUE THREAD

**Issue by ghost** [verygenericname/sshtars#3]
can you make it not auto restart when installing TrollStore or Pogo?
I am working on a script to automate some things and this is really getting in the way
I am trying to figure out where the script is in ssh.tar.gz that is doing the commands for TrollStore but I can not find it

**Comment by verygenericname** [comment]
The script it uses to install is either trollstoreinstaller or pogoinstaller in /usr/bin, the thing that automates it is not a script, it is inside /usr/local/bin/restored_external, i can try and make it like ask to restart by pressing vol up or start dropbear by pressing vol down depending on when you press

**Comment by ghost** [comment]
yes please can you do that or just send out a quick update that disables auto restart until you can do it like you said, please. i am trying to make palera1n automatically install pogo by default and automate the process of dumping blobs and all that into a simple executable that is user friendly and easy to use

**Comment by ghost** [comment]
i used a hex editor to change the restored_executable binary to replace the text `/sbin/reboot` with `/sbin/echo ` so that it is the same byte length binary and still a valid executable whilst also doing nothing in place of restarting. however when i replace the binary and regenerate the ramdisk, and boot the iphone, it says it don't like restored_external because of a codesigning error. confused as heck because it is doing amfi patches so why tf would it be complaining about codesigning of all things lol. just waiting to see if you can help me out and update it to not auto restart

**Comment by ghost** [comment]
I was able to edit the `/usr/local/bin/restored_external` binary to stop it from auto restarting. I had to run `codesign --remove-signature restored_external` first and then go into a hex editor and change it, making sure the total byte size of the binary stayed 52488 bytes. It was after modifying the binary I had to run `codesign --sign - --force --preserve-metadata=entitlements,requirements,flags,runtime restored_external` to fix the codesign error on boot. 

I was able to inject a script namely `/usr/bin/intf` to run after the trollstore installer and/ or pogo installer is done running, and I was able to make an ascii palera1n text to show after. 

My main issue now is that I can not seem to be able to get the dropbear service to run in this environment, it gives me trouble. Do you know how I can get the ssh to work after trollstore installer and/ or pogo installer has completed in the same ramdisk?

**Comment by ghost** [comment]
ok i got it to work, it was just hell trying to get it to work is all, sounds good. i submitted a pr for you
